<script setup lang="ts">
import { onMounted, ref } from 'vue';

const is_logo_broken = ref(false);
const is_animation_finished = ref(false);
const click_broken_logo = () => {
  if(is_animation_finished.value){
    is_logo_broken.value = !is_logo_broken.value;
  }
};
onMounted(() => {
    const element: HTMLElement = document.getElementById('animatedElement') as HTMLElement;
    element.addEventListener('animationend', () => {
        is_animation_finished.value = true;
    });
});
</script>
<template>
  <!-- <header v-if="is_animation_finished">
    <h1 class="text-center text-4xl font-bold text-white">Welcome to My Blog</h1>
    <p class="text-center text-lg text-gray-300">Click the logo to toggle its state!</p>
  </header> -->
  <header>
      <div>
          <h1 class="text-center text-4xl font-bold text-white">Welcome to My Blog</h1>
          <p class="text-center text-lg text-gray-300">Click the logo to toggle its state!</p>
      </div>
  </header>
    <main @click="click_broken_logo" class="wobble-hor-bottom vibrate-1">
        <img id="animatedElement" class="whole_logo whole_logo_mask_animation" src="../assets/img/chernHao_blog_logo_4_whole.png" alt="">
        <img :class="{offset_top: is_logo_broken}" src="../assets/img/chernHao_blog_logo_4_top.png" alt="">
        <img :class="{offset_bottom: is_logo_broken}" src="../assets/img/chernHao_blog_logo_4_bottom.png" alt="">
      <div v-if="is_logo_broken" class="menu_content">
        <p class="menu_item">
          <RouterLink to="/magazine">杂志</RouterLink>
        </p>
        <p  class="menu_item">
          <RouterLink to="/coding">编程</RouterLink>
        </p>
        <p  class="menu_item">
          <RouterLink to="/design">杂志</RouterLink>
        </p>
        <p  class="menu_item">
          <RouterLink to="/">主页</RouterLink>
        </p>
      </div>      
    </main>
</template>
<style lang="scss" scoped>
header{
  width: 100%;
  height: 10vh;
  text-align: center;
}
main {
    position: relative;
    width: 80%;
    height: 80vh;
    margin: auto;
    img{
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        // 
        transition: top 0.5s, left 0.5s, transform 0.5s;
    }
    .menu_content {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      width: 80%;
      height: 80%;
      color: white;
      display: flex;
      justify-content: center;
      align-items: center;
      font-size: 1.5rem;
      column-gap: 10px;
      .menu_item {
        cursor: pointer;
        padding: 10px;
        border: 1px solid white;
        border-radius: 5px;
        transition: background-color 0.3s, transform 0.3s;
      }
    }
    .whole_logo {
      mask: linear-gradient(90deg, #000 100%)
    }
}
.offset_top {
  top:35%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.offset_bottom {
  top: 65%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.whole_logo_mask_animation {
  -webkit-animation: whole_logo_mask_animation 3s linear both;
          animation: whole_logo_mask_animation 3s linear both;
}
@keyframes whole_logo_mask_animation {
  0% {
    mask: linear-gradient(90deg, #000 100%);
  }
  10%{
    mask: linear-gradient(90deg, #000 90%, transparent 90%);
  }
  20%{
    mask: linear-gradient(90deg, #000 80%, transparent 80%);
  }
  30%{
    mask: linear-gradient(90deg, #000 70%, transparent 70%);
  }
  40%{
    mask: linear-gradient(90deg, #000 60%, transparent 60%);
  }
  50%{
    mask: linear-gradient(90deg, #000 50%, transparent 50%);
  }
  60%{
    mask: linear-gradient(90deg, #000 40%, transparent 40%);
  }
  70%{
    mask: linear-gradient(90deg, #000 30%, transparent 30%);
  }
  80%{
    mask: linear-gradient(90deg, #000 20%, transparent 20%);
  }
  90%{
    mask: linear-gradient(90deg, #000 10%, transparent 10%);
  }
  100% {
    mask: linear-gradient(90deg, #000 0%, transparent 0%);
    display: none;
  }
}

.vibrate-1 {
	-webkit-animation: vibrate-1 0.3s 3 linear both;
	        animation: vibrate-1 0.3s 3 linear both;
  // -webkit-animation-duration: 1s;
  //         animation-duration: 1s;        
}

/* ----------------------------------------------
 * Generated by Animista on 2025-6-16 16:26:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-1
 * ----------------------------------------
 */
@-webkit-keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}
@keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}

.wobble-hor-bottom {
	-webkit-animation: wobble-hor-bottom 0.5s 3 both;
	        animation: wobble-hor-bottom 0.5s 3 both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-6-16 16:49:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-bottom
 * ----------------------------------------
 */
@-webkit-keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
            transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
            transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
            transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
            transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
            transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
            transform: translateX(-6px) rotate(-1.2deg);
  }
}
@keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
            transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
            transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
            transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
            transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
            transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
            transform: translateX(-6px) rotate(-1.2deg);
  }
}

</style>